language: python
# List of Python and Django version combinations to test
matrix:
  fast_finish: true
  include:
    - python: 2.6
      env: DJANGO_VERSION=1.4.*
    - python: 2.6
      env: DJANGO_VERSION=1.5.*
    - python: 2.6
      env: DJANGO_VERSION=1.6.*
    - python: 2.7
      env: DJANGO_VERSION=1.4.*
    - python: 2.7
      env: DJANGO_VERSION=1.5.*
    - python: 2.7
      env: DJANGO_VERSION=1.6.*
    - python: 2.7
      env: DJANGO_VERSION=1.7.*
    - python: 2.7
      env: DJANGO_VERSION=1.8.*
    - python: 3.2
      env: DJANGO_VERSION=1.5.*
    - python: 3.2
      env: DJANGO_VERSION=1.6.*
    - python: 3.2
      env: DJANGO_VERSION=1.7.*
    - python: 3.2
      env: DJANGO_VERSION=1.8.*
    - python: 3.3
      env: DJANGO_VERSION=1.5.*
    - python: 3.3
      env: DJANGO_VERSION=1.6.*
    - python: 3.3
      env: DJANGO_VERSION=1.7.*
    - python: 3.3
      env: DJANGO_VERSION=1.8.*
    - python: 3.4
      env: DJANGO_VERSION=1.7.*
    - python: 3.4
      env: DJANGO_VERSION=1.8.*
    - python: 3.2
      env: DJANGO_VERSION=1.5.*
    - python: 3.2
      env: DJANGO_VERSION=1.6.*
    - python: 3.2
      env: DJANGO_VERSION=1.7.*
    - python: 3.2
      env: DJANGO_VERSION=1.8.*
    - python: 3.3
      env: DJANGO_VERSION=1.5.*
    - python: 3.3
      env: DJANGO_VERSION=1.6.*
    - python: 3.3
      env: DJANGO_VERSION=1.7.*
    - python: 3.3
      env: DJANGO_VERSION=1.8.*
    - python: 3.4
      env: DJANGO_VERSION=1.7.*
    - python: 3.4
      env: DJANGO_VERSION=1.8.*
# command to install Django
install:
  - pip install -q six
  - pip install -q Django==$DJANGO_VERSION
# command to run tests
script: python test/test.py
